apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: scanner:dev
            imagePullPolicy: IfNotPresent